require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-airbnb
  
AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'Gemfile.lock'
    - 'config.ru'

Rails/EnumHash:
 Enabled: false

inherit_from:
  - .rubocop_airbnb.yml
