require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'Gemfile.lock'
    - 'config.ru'
    - 'db/migrate/20220120101655_create_active_storage_tables.active_storage.rb'
    - 'db/migrate/20220128234636_devise_token_auth_create_users.rb'
    - 'db/migrate/20220120124837_create_profiles.rb'

inherit_from:
  - .rubocop_airbnb.yml

Layout/LineLength:
  Max: 150
